apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-${CLUSTER_NAME}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/${CLUSTER_NAME}: "owned"
  amiSelectorTerms:
    - id: "${AMD_AMI_ID}"
  blockDeviceMappings:
    - deviceName: "/dev/xvda"
      ebs:
        volumeSize: "100Gi"
        volumeType: "gp3"
